### ISSUE TITLE
Congrats, definetly a must have for music collection refiner

### ISSUE THREAD

**Issue by chourmovs** [Polochon-street/bliss-metric-learning#4]
Will test and follow it closely

**Comment by chourmovs** [comment]
closed

**Comment by Polochon-street** [comment]
thanks! Looking forward for opinions on it, not sure how well it performs so far :)

**Comment by chourmovs** [comment]
I'll slightly divert use of your tool to see how it can help in building ideal playlist starting from a lage databe

`you will point the odd-one-out, e.g. the song that is most dissimilar in the three songs that will be presented to you.`
will become for my project
you will point the odd-one-out, e.g. the song that is most **unpleasant** for you in the three songs that will be presented to you.

As context, I try to slightly automatise webradio station, i've already a script using last.fm popularity fetch, I intend to complete it

**Comment by chourmovs** [comment]
I bet a lot on this statement

> Finally, it is possible to plug this distance matrix M into bliss / blissify, and make playlists using it. It should be more tailored to the user's tastes than the default identity matrix.
